[build]
  
  base = "your_base_directory/"

 
  command = "npm run build"

  
  publish = "public/"

 
  cache = { paths = ["node_modules"] }

[context.production.environment]
  
  NODE_ENV = "production"

[context.deploy-preview.environment]
  
  NODE_ENV = "development"