[build]
  
  base = "myPortfolio"

 
  command = "npm run build"

  
  publish = "dist"

 
  cache = { paths = ["node_modules"] }

[context.production.environment]
  
  NODE_ENV = "production"

[context.deploy-preview.environment]
  
  NODE_ENV = "development"
